name: Blerina Shkodra
favicon: null
layout_spectrum: 0.29191
typography_spectrum: 0.44587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95a6d2'
    - '#9ca9d3'
    - '#9aa7d4'
    - '#99a7d1'
    - '#9aa7d2'
  brandStrength: 0.3125
  lightness: 0.9842406220268458
  saturation: 0.9375
  rhythmicContrast: 0.029412718024104834
purpose: []
