name: Blerina Shkodra
favicon: null
layout_spectrum: 0.29191
typography_spectrum: 0.44587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc8e6'
    - '#ebc4c9'
    - '#6e92c2'
    - '#b97c86'
    - '#575e57'
  brandStrength: 0.3125
  lightness: 0.9842406220268458
  saturation: 0.9375
  rhythmicContrast: 0.029412718024104834
purpose: []
